-- Print the full description of the books table
SELECT 
    C.COLUMN_NAME AS 'COLUMN NAME', 
    C.COLUMN_TYPE AS 'COLUMN TYPE', 
    C.IS_NULLABLE AS 'IS NULLABLE', 
    C.COLUMN_KEY AS 'COLUMN KEY', 
    C.COLUMN_DEFAULT AS 'COLUMN DEFAULT', 
    C.EXTRA AS 'EXTRA',
    IFNULL(TC.CONSTRAINT_TYPE, 'NONE') AS 'CONSTRAINT TYPE'
FROM 
    INFORMATION_SCHEMA.COLUMNS C
LEFT JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU ON C.TABLE_SCHEMA = KCU.TABLE_SCHEMA AND C.TABLE_NAME = KCU.TABLE_NAME AND C.COLUMN_NAME = KCU.COLUMN_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC ON KCU.CONSTRAINT_SCHEMA = TC.CONSTRAINT_SCHEMA AND KCU.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
WHERE 
    C.TABLE_SCHEMA = DATABASE() 
    AND C.TABLE_NAME = 'books';
