USE alx_book_store;

-- SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA
SELECT 
    C.COLUMN_NAME AS 'COLUMN NAME', 
    C.COLUMN_TYPE AS 'COLUMN TYPE', 
    C.IS_NULLABLE AS 'IS NULLABLE', 
    C.COLUMN_KEY AS 'COLUMN KEY', 
    C.COLUMN_DEFAULT AS 'COLUMN DEFAULT', 
    C.EXTRA AS 'EXTRA',
    IFNULL(TC.CONSTRAINT_TYPE, 'NONE') AS 'CONSTRAINT TYPE'
FROM alx_book_store.COLUMNS
WHERE TABLE_SCHEMA = 'alx_book_store'
AND TABLE_NAME = 'books';

